# keywords.py
KEYWORDS = {
    "rice", "wheat", "flour", "lentils", "chickpeas", "paneer", "yogurt", "ghee", "milk",
    "coconut", "tamarind", "garlic", "ginger", "onions", "tomatoes", "potatoes", "spinach",
    "chicken",
    "biryani",
    "water",
    "marinate",
    "Thirthi's masalas",
    "long",
    "Chowitri's",
    "Badian's",
    "turmeric salt",
    "powder",
    "dhania powder",
    "tikka lal mirch powder",
    "chambacal mirch powder",
    "masala powder",
    "haldi powder",
    "black cardamom",
    "adrak-lahsun paste",
    "yogurt",
    "curd",
    "oil",
    "warm",
    "piece",
    "baricade cut",
    "browned",
    "fried onion",
    "potato",
    "masalas",
    "small green elaichi",
    "dalchini",
    "tej patta",
    "chisel",
    "shahi jeera",
    "brown",
    "elaichi powder",
    "garnish",
    "cook",
    "masala",
    "rice",
    "food color",
    "fried onions",
    "half dal",
    "biryani masala",
    "baricade-cut pudina",
    "coriander",
    "dum",
    "high flame",
    "low flame",
    "rice",
    "gms",
    "kgms",
    "wheat",
    "flour",
    "lentils",
    "chickpeas",
    "paneer",
    "yogurt",
    "ghee",
    "milk",
    "coconut",
    "tamarind",
    "garlic",
    "ginger",
    "onions",
    "tomatoes",
    "potatoes",
    "spinach",
    "cucumber",
    "carrot",
    "peas",
    "beans",
    "mustard seeds",
    "cumin seeds",
    "fenugreek",
    "coriander",
    "mint",
    "curry leaves",
    "asafoetida",
    "saffron",
    "cashews",
    "almonds",
    "raisins",
    "coconut milk",
    "poppy seeds",
    "pomegranate",
    "turmeric",
    "chili powder",
    "garam masala",
    "cumin powder",
    "coriander powder",
    "black pepper",
    "cardamom",
    "cloves",
    "bay leaf",
    "cinnamon",
    "mustard",
    "fennel seeds",
    "red chili",
    "tamarind paste",
    "jaggery",
    "salt",
    "sugar",
    "frying",
    "boiling",
    "steaming",
    "roasting",
    "grilling",
    "sautéing",
    "baking",
    "pressure cooking",
    "stir-frying",
    "tempering",
    "marinating",
    "blending",
    "grinding",
    "whisking",
    "biryani",
    "butter chicken",
    "palak paneer",
    "chole",
    "dal",
    "samosa",
    "pakora",
    "aloo gobi",
    "masoor dal",
    "korma",
    "dosa",
    "idli",
    "vada",
    "chapati",
    "naan",
    "paratha",
    "pulao",
    "chicken",
    "seconds",
    "minutes",
    "seconds",
    "minutes",
    "marinate",
    "pani puri",
    "chole bhature",
    "tandoori chicken",
    "malai kofta",
    "rogan josh",
    "lassi",
    "kheer",
    "pressure cooker",
    "tawa",
    "kadhai",
    "chakla",
    "belan",
    "tandoor",
    "gravy boat",
    "spatula",
    "mortar and pestle",
    "grinder",
    "strainer",
    "mixing bowl",
    "pan",
    "pot",
    "frying pan",
    "north indian",
    "south indian",
    "street food",
    "vegetarian",
    "non-vegetarian",
    "vegan",
    "raw",
    "steamed",
    "spicy",
    "sweet",
    "mild",
    "traditional",
    "fusion",
    "punjabi",
    "gujarati",
    "bengali",
    "rajasthani",
    "kashmiri",
    "andhra",
    "tamil",
    "kerala",
    "goan",
    "hyderabadi",
    "lucknowi",
}
